#!/usr/bin/env bash

sudo apt-get update && sudo apt-get install -y \
    build-essential \
    perl \
    python3 \
    ninja-build \
    libssl-dev \
    zlib1g-dev \
    libx11-dev \
    libxext-dev \
    libxfixes-dev \
    libxrender-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    libxcb1-dev \
    libx11-xcb-dev \
    libxcb-keysyms1-dev \
    libxcb-image0-dev \
    libxcb-shm0-dev \
    libxcb-icccm4-dev \
    libxcb-sync-dev \
    libxcb-xfixes0-dev \
    libglu-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    mesa-common-dev \
    libgbm-dev \
    libwayland-dev \
    libwayland-cursor0 \
    libwayland-egl1-mesa \
    libfreetype6-dev \
    libfontconfig1-dev \
    libpng-dev \
    libjpeg-dev \
    libasound2-dev \
    libpulse-dev \
    libproxy-dev \
    ca-certificates \
    libicu-dev
