name: build-ios 
on:
  push:
    branches:
      - main
      - debug-ios-ci
      - debug-release
    tags:
      - v*

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
#      - uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: '14.3.1'
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Upterm debug"
        if: contains(github.ref_name, 'debug-ios-ci') 
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
      - run: ./build_ios.sh
      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: Archive Build
          path: /Users/runner/work/qt5-builder/QtBuild
  release: 
    name: Release
    runs-on: ubuntu-latest 
    needs: build-ios
    if: github.ref_type == 'tag' or contains(github.ref, 'debug-release')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Archive Build
      - name: "Upterm debug"
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
      - name: Upload Build to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./QtBuild/*
          tag: ${{ github.ref }}
          overwrite: true

