name: build-linux
on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  QT_PREFIX: "/home/runner/work/qt5-builder/QtBuild"

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x build_linux.sh install_dependencies.sh

      - name: Add 16G swap to reduce OOM risks
        run: |
          sudo fallocate -l 16G /swapfile || sudo dd if=/dev/zero of=/swapfile bs=1G count=16
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo sysctl vm.swappiness=10

      - name: Install Dependencies
        run: | 
          sudo apt-get update && \
          sudo apt-get install -y \
            build-essential ninja-build pkg-config perl openjdk-11-jdk \
            libx11-dev libxext-dev libxrandr-dev libxi-dev libxrender-dev \
            libxfixes-dev libxcursor-dev libxtst-dev libgl-dev libglu-dev \
            libssl-dev libdbus-1-dev libpulse-dev flex bison gperf \
            libfontconfig1-dev libfreetype6-dev libx11-xcb-dev libxcb1-dev \
            libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev \
            libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev \
            libxcb-randr0-dev libxcb-render-util0-dev \
            libxkbcommon-dev libxkbcommon-x11-dev libfontconfig-dev \
            libdrm-dev libxcomposite-dev libxss-dev

      - name: Install Dependencies for linux
        run: ./install_dependencies.sh

      - name: "Upterm debug"
        if: contains(github.ref_name, 'debug-android-ci')
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
        
      - name: Get OpenSSL
        run: |
              wget https://github.com/KDAB/android_openssl/archive/refs/heads/master.zip
              unzip master.zip
              mv android_openssl-master android_openssl

      - name: Download Qt and extract it
        run: |
          git clone --branch v5.15.16-lts-lgpl https://invent.kde.org/qt/qt/qt5.git
          cd qt5
          perl init-repository
      
      - name: Build Qt Linux
        run: |
           echo ${{env.QT_PREFIX}}
           ./build_linux.sh

      - name: Install Qt Linux
        run: |
          echo "${QT_PREFIX}/bin" >> $GITHUB_PATH
          cd qt5 && sudo make install
      
      - name: make Qt Webview
        run: |
          ./configure -c++std c++17 -ssl -openssl-linked -I "/home/runner/work/master/android_openssl/ssl_3/include" -L "/home/runner/work/master/android_openssl/ssl_3" -opensource -confirm-license -release -nomake tests -nomake examples -skip qtmultimedia -skip qtpurchasing -no-webengine-jumbo-build -no-warnings-are-errors -no-opengl -qt-libjpeg -qt-libpng -prefix /home/runner/work/qt5-builder/QtBuild
          make -j"$(nproc)"
      
      - name: Install Qt Webview Build
        run: | 
          cd qt5 && sudo make install

      - name: "Archive Build"
        uses: actions/upload-artifact@v4
        with:
          name: Archive Build
          path: /home/runner/work/qt5-builder/QtBuild

      - name: "Tar Build"
        run: tar -czvf Qt-5.15-16-linux.tar.gz -C /home/runner/work/qt5-builder/QtBuild .

      - name: "Upload Build to release"
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          file: Qt-5.15-16-linux.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
