name: build-linux
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x build_linux.sh install_dependencies.sh

      - name: Install Dependencies
        run: | 
          sudo apt-get update && \
          sudo apt-get install -y \
            build-essential ninja-build pkg-config perl openjdk-11-jdk \
            libx11-dev libxext-dev libxrandr-dev libxi-dev libxrender-dev \
            libxfixes-dev libxcursor-dev libxtst-dev libgl-dev libglu-dev \
            libssl-dev libdbus-1-dev libpulse-dev flex bison gperf \
            libfontconfig1-dev libfreetype6-dev libx11-xcb-dev libxcb1-dev \
            libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev \
            libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev \
            libxcb-randr0-dev libxcb-render-util0-dev \
            libxkbcommon-dev libxkbcommon-x11-dev libfontconfig-dev \
            libdrm-dev libxcomposite-dev libxss-dev \
            libgtk-3-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libasound2-dev \
            libv4l-dev \
            libnss3-dev \
            libxtst-dev \
            libudev-dev \
            libappindicator3-dev \
            libxss-dev

      - name: Install Dependencies for linux
        run: ./install_dependencies.sh

      - name: "Upterm debug"
        if: contains(github.ref_name, 'debug-android-ci')
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
        
      - name: Get OpenSSL
        run: |
              wget https://github.com/KDAB/android_openssl/archive/refs/heads/master.zip
              unzip master.zip
              mv android_openssl-master android_openssl

      - name: Download Qt and extract it
        run: |
          git clone --branch kde/5.15 https://invent.kde.org/qt/qt/qt5.git
          cd qt5
          perl init-repository
      
      - name: Build Qt Linux
        run: |
          ./build_linux.sh

      - name: Install Qt Linux
        run: |
          cd qt5 && sudo make install
            
      - name: "Archive Build"
        uses: actions/upload-artifact@v4
        with:
          name: Archive Build
          path: /home/runner/work/qt5-builder/QtBuild

      - name: "Tar Build"
        run: tar -czvf Qt-5.15-17-linux.tar.gz -C /home/runner/work/qt5-builder/QtBuild .

      - name: "Upload Build to release"
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          file: Qt-5.15-17-linux.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
