name: build-ios 
on:
  push:
    branches:
      - main
      - debug-ios-ci
      - debug-release
    tags:
      - v*

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
#      - uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: '14.3.1'
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Upterm debug"
        if: contains(github.ref_name, 'debug-ios-ci')
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
      - run: ./build_ios.sh
      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: Archive Build
          path: /Users/runner/work/qt5-builder/QtBuild
      - name: Tar Build
        run: tar -czvf Qt-5.15-14-macos.tar.gz -C /Users/runner/work/qt5-builder/QtBuild .
      - name: Upload Build to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: Qt-5.15-14-macos.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
            #      - name: "Upterm debug"
            #        if: contains(github.ref_name, 'debug-release')
            #        uses: owenthereal/action-upterm@v1
            #        with:
            #          limit-access-to-actor: true


