name: build-linux
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x build_linux.sh install_dependencies.sh

      - name: Install Dependencies
        run: ./install_dependencies.sh

      - name: "Upterm debug"
        if: contains(github.ref_name, 'debug-android-ci')
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
        
      - name: Get OpenSSL
        run: |
              wget https://github.com/KDAB/android_openssl/archive/refs/heads/master.zip
              unzip master.zip
              mv android_openssl-master android_openssl

      - name: Download Qt and extract it
        run: |
          git clone --branch v5.15.16-lts-lgpl https://invent.kde.org/qt/qt/qt5.git
          cd qt5
          perl init-repository
      
      - name: Build Qt Linux
        run: ./build_linux.sh

      - name: Install Qt Linux
        run: cd qt5 && sudo make install

      - name: "Archive Build"
        uses: actions/upload-artifact@v4
        with:
          name: Archive Build
          path: /home/runner/work/qt5-builder/QtBuild

      - name: "Tar Build"
        run: tar -czvf Qt-5.15-16-linux.tar.gz -C /home/runner/work/qt5-builder/QtBuild .

      - name: "Upload Build to release"
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          file: Qt-5.15-16-linux.tar.gz
          tag: ${{ github.ref }}
          overwrite: true